# Generated by Django 5.1.6 on 2025-06-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='explanation',
        ),
    ]
