# Generated by Django 5.1.6 on 2025-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskbank', '0002_remove_solution_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='extension',
        ),
    ]
